name: Deploy Chrome
on:
  push:
    branches:
    - master
jobs:
  deploy:
    if: startsWith(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    env:
      CHROME_APP_ID: fkjghajhfjamfjcmdkbangbeogbagnjf
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - run: npm ci
    - run: npm test
    - run: npm run build:chrome
    - run: zip -r package.zip .
      working-directory: app/build/chrome
    - uses: mikeyaworski/chrome-addon@master
      with:
        extension: ${{ env.CHROME_APP_ID }}
        zip: app/build/chrome/package.zip
        client-id: ${{ secrets.CHROME_CLIENT_ID }}
        client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
        refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
